#!/bin/sh -e
#
# reportbug helper for smartmontools
#
# check what IDE_TASK options are set in the kernel:

echo "Output of $0:" >&3
CONFIG=/boot/config-`uname -r`
if [ -r "$CONFIG" ]; then
	grep IDE_TASK $CONFIG >&3
else
	echo "Couldn't parse $CONFIG" >&3
fi
